CREATE TABLE LIVRES (
	ID SERIAL PRIMARY KEY,
	TITRE VARCHAR(255) NOT NULL,
	AUTEUR VARCHAR(255) NOT NULL,
	NOMBRE_PAGES INT,
	GENRE VARCHAR(100),
	DATE_PUBLICATION DATE,
	STATUT_LECTURE VARCHAR(50),
	COUVERTURE BYTEA,
	FICHIER_EBOOK BYTEA,
	FORMAT_EBOOK VARCHAR(10)
);